// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdppgtleqftlqesijfvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkcHBndGxlcWZ0bHFlc2lqZnZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MTI3MzksImV4cCI6MjA1OTk4ODczOX0.vsDI-Z0sl8kcSdoxCHDTq33VG7mq2sTRk2pNBR_mGlw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);